[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/sign-in"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/sign-up"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SITE_URL = "https://applymate.app"
  VITE_SUPABASE_URL = "https://qiowwdewasasyilriyfn.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpb3d3ZGV3YXNhc3lpbHJpeWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5Njg5NjgsImV4cCI6MjA0OTU0NDk2OH0.sBuZXEglaylseHuJjWuAQhmVcj6ipU85TsWzM2C4Owc"
  # Clerk environment variables - set these in Netlify dashboard
  VITE_CLERK_PUBLISHABLE_KEY = "" # Set in Netlify dashboard
  VITE_CLERK_FRONTEND_API = "" # Set in Netlify dashboard

[functions]
  external_node_modules = ["@langchain/community", "@langchain/openai", "cheerio", "zod"]
  # Include OpenAI API key in function environment
  [functions.environment]
    OPENAI_API_KEY = "sk-xxxxxxxxxxxxxxxxxxxxxxxx"  # Replace with actual key in Netlify dashboard
