[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.production]
  environment = { NODE_ENV = "production" }

[context.develop]
  environment = { NODE_ENV = "development" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    # Allow Clerk domains
    Content-Security-Policy = "frame-ancestors 'self' https://accounts.applymate.app https://exact-viper-93.accounts.dev https://*.clerk.accounts.dev"
    X-Frame-Options = "ALLOW-FROM https://accounts.applymate.app https://exact-viper-93.accounts.dev"

# Production redirects
[context.production]
  [[redirects]]
    from = "/sign-in"
    to = "https://accounts.applymate.app/sign-in"
    status = 301
    force = true
    conditions = {context = "production"}

  [[redirects]]
    from = "/sign-up"
    to = "https://accounts.applymate.app/sign-up"
    status = 301
    force = true
    conditions = {context = "production"}

# Development/Staging redirects
[context.develop]
  [[redirects]]
    from = "/sign-in"
    to = "https://exact-viper-93.accounts.dev/sign-in"
    status = 301
    force = true
    conditions = {context = "develop"}

  [[redirects]]
    from = "/sign-up"
    to = "https://exact-viper-93.accounts.dev/sign-up"
    status = 301
    force = true
    conditions = {context = "develop"}

# Common redirects (for both environments)
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/jobs"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/archived"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {exclude = ["/*.png", "/*.ico", "/*.svg"]}}

[functions]
  external_node_modules = ["@langchain/community", "@langchain/openai", "cheerio", "zod"]
  node_bundler = "esbuild"
