[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/sign-in"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/sign-up"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/jobs"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/archived"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {exclude = ["/*.png", "/*.ico", "/*.svg"]}}

[build.environment]
  VITE_SITE_URL = "https://applymate.app"
  # Environment variables are managed in Netlify dashboard

[functions]
  external_node_modules = ["@langchain/community", "@langchain/openai", "cheerio", "zod"]
  # Include OpenAI API key in function environment
  [functions.environment]
    OPENAI_API_KEY = "sk-xxxxxxxxxxxxxxxxxxxxxxxx"  # Replace with actual key in Netlify dashboard
