[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.production]
  environment = { NODE_ENV = "production" }

[context.develop]
  environment = { NODE_ENV = "development" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/sign-in"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/sign-up"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/jobs"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/archived"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {exclude = ["/*.png", "/*.ico", "/*.svg"]}}

[functions]
  external_node_modules = ["@langchain/community", "@langchain/openai", "cheerio", "zod"]
  node_bundler = "esbuild"
